### PR TITLE
Add cell tooltip for usability

### PR DESCRIPTION
**Pull request by jschroedl**
Show configuration and property details in cell tooltip to save a lot of
mouse movement. Helps avoid mistakenly changing the wrong setting when
the property grid is dense.

### CODE REVIEW

**Comment by tom-englert** [comment]
A great idea! 
However I would prefer it done in XAML, so we can pimp up the tool tip, like in https://github.com/tom-englert/ProjectConfigurationManager/commit/ab35c49642b453b146015de0ae8744dffd05f71c
Hope you don't mind :smile:

**Comment by jschroedl** [comment]
That's an even better fix. Thanks! I was not certain how to get the Data Context right to pull it off in XAML and your solution lets other devs style it if desired.

**Comment by tom-englert** [comment]
P.S. If you like this tool you could give some stars here, to make it more visible to the public: https://visualstudiogallery.msdn.microsoft.com/cf7efe17-ae87-40fe-a1e2-f2d61907f043/view/Reviews

**Comment by jschroedl** [comment]
Indeed! How did I forget to do that. Done! Thanks again for the cool tool.  

I still plan to debug some more as it does not show the configurations for one of the projects in our main solution.

**Comment by tom-englert** [comment]
:smile:

**Pull request closed without merging**
